version: 2.1
orbs:
  node: circleci/node@5.0.3
  aws-ecr: circleci/aws-ecr@8.1.2
jobs:
  test:
    executor:
      name: node/default
      tag: 16.14.2
    steps:
    - checkout

    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}

    # - node/install-packages:
    #     pkg-manager: npm
    
    - run: 
          name: Install Dependencies
          command: npm install

    # - save_cache:
    #     key: dependency-cache-{{ checksum "package.json" }}
    #     paths:
    #       - node_modules

    - run:
        name: Run Tests
        command: npm test

workflows:
  test_build_deploy:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          repo: slackcicd
          tag: "latest,v0.1.${CIRCLE_BUILD_NUM}"
          dockerfile: Dockerfile
          path: .
          requires:
            - test